FROM apache/airflow:2.9.1

USER root

RUN apt-get update && apt-get install -y \
    openjdk-17-jre-headless \
    && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

USER airflow

RUN pip install --no-cache-dir \
    kaggle==1.6.17 \
    boto3==1.35.0 \
    pyspark==3.5.1 \
    pyarrow==17.0.0 \
    pandas==2.2.3 \
    psycopg2-binary==2.9.10
